Exception should be caught by reference.